name: MDFlareAgent
options:
  bundleIdPrefix: com.mdflare
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "16.0"
settings:
  base:
    PRODUCT_NAME: MDFlare Agent
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"
targets:
  MDFlareAgent:
    type: application
    platform: macOS
    sources:
      - Sources
    settings:
      base:
        INFOPLIST_FILE: Sources/Info.plist
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Manual
        PRODUCT_BUNDLE_IDENTIFIER: com.mdflare.agent
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        LSUIElement: true
